### ISSUE TITLE
Could Not Load

### ISSUE THREAD

**Issue by rabelution** [na-ka-na/ExcelCompare#19]
Getting this error when trying to compare files: 
'Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer' 

Downloaded the latest version just a few minutes ago.. I have this script on my home desktop and it works perfectly.

**Comment by MassiveHiggsField** [comment]
Which java version are you using?

**Comment by rabelution** [comment]
the latest version;
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by na-ka-na** [comment]
By any chance did you download the source instead of the binary?
