### ISSUE TITLE
FeatureRequest: compare numbers with a given precision

### ISSUE THREAD

**Issue by luigikitten** [na-ka-na/ExcelCompare#22]
Hi,
    this is a great tool, and I would like to use it against some computed files.
Sadly, I get thousand of false errors, like:

DIFF  Cell at     MyTab!M79 => '979.1358516266992' v/s '979.1358516266946'

Would it be possible to put a threshold when comparing numbers?

Thanks!
Luigi

**Comment by na-ka-na** [comment]
Yes, this is should be doable, I'll take it up for the next release.

**Comment by na-ka-na** [comment]
Added a --diff_numeric_precision flag. Released 0.5.0.

**Comment by luigikitten** [comment]
Many thanks!!! I will check it asap
