### ISSUE TITLE
Flag --diff_numeric_precision not working

### ISSUE THREAD

**Issue by luigikitten** [na-ka-na/ExcelCompare#25]
Hi,
   I am not able to use the flag --diff_numeric_precision (using release 0.5.1):

..\ExcelCompare\excel_cmp.bat --diff_numeric_precision=0.1 a.xls b.xls
File: --diff_numeric_precision=0.01 does not exist.

..\ExcelCompare\excel_cmp.bat a.xls b.xls --diff_numeric_precision=0.1 
I get the old diff with many "equal" values, like:
DIFF  Cell at     Planned Fee - All Events!J77 => '56370.68544061038' v/s '56370.685440610396'
DIFF  Cell at     Planned Fee - All Events!J78 => '56370.68544061038' v/s '56370.685440610396'
DIFF  Cell at     Planned Fee - All Events!D79 => '76523.98000000001' v/s '76523.98'
DIFF  Cell at     Planned Fee - All Events!G79 => '76523.98000000001' v/s '76523.98'

thanks
Luigi

**Comment by na-ka-na** [comment]
Are you sure you used 0.5.1? Coz its working for me:

bin/excel_cmp --diff_numeric_precision=0.01
test/resources/ss1_numeric_precision.xlsx
test/resources/ss2_numeric_precision.xlsx

maybe it doesn't work on windows? but code is exactly the same.

**Comment by luigikitten** [comment]
Hi,
   sorry my fault :) I simply unzipped the new release over the old folder.
Doing this in the "dist" folder i got both

ExcelCompare-0.5.1.jar
ExcelCompare-0.4.3.jar

It seems that the .bat picked the old one. After removing past version, it
works.
Many thanks and sorry for the noise
Luigi
