### ISSUE TITLE
Update README with --diff_numeric_precision

### ISSUE THREAD

**Issue by innominate227** [na-ka-na/ExcelCompare#27]
It would be nice if the tool could skip reporting very small numeric differences (eg reporting 0.000001 vs 0.000002)

You could optionally specify a threshold on the command line that if specified would only report numeric differences greater than the threshold.  (eg specifing "--numeric-threshold 0.001") would prevent the example above from being reported.

Great Tool.
Thanks

**Comment by na-ka-na** [comment]
There already is a flag --diff_numeric_precision ... seems I've forgotten to update the main help page.

**Comment by na-ka-na** [comment]
Done, added to README.
