### ISSUE TITLE
Command not found.

### ISSUE THREAD

**Issue by CLKCrompton** [na-ka-na/ExcelCompare#28]
Hi,

I've been careful to download Excel Compare 0.5.1, and not its binary.  I've unzipped the file, put it bin in my path, but when I run it I'm getting a  excel_cmp: command not found errors. 

I'm running java 1.8.0_60.
Any pointers?

**Comment by na-ka-na** [comment]
Where did you download it from? Did you download the release binary from
here - https://github.com/na-ka-na/ExcelCompare/releases ?

**Comment by CLKCrompton** [comment]
Hi,
Oh, yes, I had downloaded the non-binary zip file from  https://github.com/na-ka-na/ExcelCompare/releases
