### ISSUE TITLE
How to compare only Excel values without formulas?

### ISSUE THREAD

**Issue by BalakrishnanNarayanaswamy** [na-ka-na/ExcelCompare#32]
Is there a way to compare only the shown values, without comparing the formulas behind them?
In our application the formulas change but not the values. It would be great if there was an ignore option for formulas.

**Comment by na-ka-na** [comment]
I think I should be able to add that. Will look into it.

**Comment by BalakrishnanNarayanaswamy** [comment]
Thank you!!

**Comment by na-ka-na** [comment]
I just released 0.6.0 with --diff_ignore_formulas flag. Let me know if you see any issues.
