### ISSUE TITLE
How to run execel comparison?

### ISSUE THREAD

**Issue by RaviAutomation** [na-ka-na/ExcelCompare#33]
Hello,

1. Can you add more details where to put excel files and from where we can execute them? where we can see shell script ?

2.when i run ,it is throwing error like file 2 not found

what is th exact process i need to follow?

**Comment by na-ka-na** [comment]
1. Excel files can be anywhere. You need to provide path to them to the shell script. It can be either full path or relative path to your current directory. Shell script is packaged in the download zip link. Please follow README with examples section. If something is not clear, point out which section.

2. Please give more details.

Process is simple: follow https://github.com/na-ka-na/ExcelCompare#installation, then follow usage. If something is not clear, point out which section.

**Comment by RaviAutomation** [comment]
Thank you for the reply but am not clear how to run this to compare files.i can see 2 files under "bin " folder ,they are "excel_cmp" and "excel_cmp.bat" but i have doubts here
1.Which file i can use either "excel_cmp.bat" or "excel_cmp"?
2. What is the purpose of these 2 files?
3. shall i add the command line in BAT file to pass excel comparison as follows,
```
@ECHO OFF
SETLOCAL
set dirname=%~dp0
java -ea -Xmx512m -cp "%dirname%\dist\*;" com.ka.spreadsheet.diff.SpreadSheetDiffer %*
ENDLOCAL
excel_cmp 1.xlsx 2.xlsx
```
OR 
```
if [ -L $0 ];then
dir=`readlink -f $0|xargs dirname`
else
dir=`dirname $0`
fi
java -ea -Xmx512m -cp "$dir/dist/*" com.ka.spreadsheet.diff.SpreadSheetDiffer "$@"
$ excel_cmp <diff-flags> <file1> <file2>
```

4,Is it possible to generate the output results in html format?

Thanks In Advance,
Ravi

**Comment by na-ka-na** [comment]
1. Use the .bat file on Windows, non bat file on Linux, Mac.
2. They are scripts to run the tool.
3. You do not need to modify any of the scripts in bin directory to run the tool. On command line just invoke bin/excel_cmp.bat <path to file1> <path to file2>
4. No

**Comment by RaviAutomation** [comment]
Thank you for quick response.
I have tried the below way but it run infinite loop with printing same out put couple of times on the cmd screen. i manually killed the process to stop the comparison.am i doing anything wrong here?

```
@ECHO OFF
SETLOCAL
set dirname=%~dp0
java -ea -Xmx512m -cp "%dirname%\dist\*;" com.ka.spreadsheet.diff.SpreadSheetDiffer %*
excel_cmp Myfile.xlsx Myfile2.xlsx
ENDLOCAL
```

**Comment by na-ka-na** [comment]
Yes that script is wrong. You should remove the line 'excel_cmp Myfile.xlsx Myfile2.xlsx' from it. Not sure what you are trying to do, you don't need that script. Here's how to run on windows: open cmd shell and type the command:

<path to ExcelCompare>/bin/excel_cmp.bat Myfile.xlsx Myfile2.xlsx

**Comment by RaviAutomation** [comment]
Thank you for giving cleared example that how to run, its working as expected
