### ISSUE TITLE
Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer

### ISSUE THREAD

**Issue by amistry1921** [na-ka-na/ExcelCompare#35]
I am running windows 7, with the following java version:
Java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode) 

And when I try to run the following command(under script folder):
excel_cmp 1.xlsx 2.xlsx (Where 1.xlsx and 2.xlsx are two excel files that I copied inside script folder)

I keep getting an error:
Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer 

Any help would be really appreciated!!

**Comment by na-ka-na** [comment]
can you try running the java command directly. cd into bin directory and run:

$> cd path\to\excelcompare\bin
$> java -ea -Xmx512m -cp "dist/*" com.ka.spreadsheet.diff.SpreadSheetDiffer 1.xlsx and 2.xlsx

**Comment by amistry1921** [comment]
I dont see any bin folder under ExcelCompare-0.6.0 folder
If I am supposed to have one, where can I find it ??
Maybe this could be the issue of that error, that I keep on getting.

**Comment by na-ka-na** [comment]
Yes its supposed to be there. Download this zip https://github.com/na-ka-na/ExcelCompare/releases/download/0.6.0/ExcelCompare-0.6.0.zip.

**Comment by amistry1921** [comment]
Yes, it works !!! Thank you !!! 
All I was missing was that bin folder !!
