### ISSUE TITLE
Supporting unified format support

### ISSUE THREAD

**Issue by lmazardo** [na-ka-na/ExcelCompare#37]
Hello,

Thanks for your great work. :+1:
Now I use everyday excelCompare on my Linux box.
I've integrated with git diff command, here is a gist for [linux integration](https://gist.github.com/lmazardo/11841cf5b037ee4338a008e55bf011af).

I think it could be useful to add [unified format output](http://ftp.gnu.org/old-gnu/Manuals/diffutils-2.8.1/html_mono/diff.html#Unified%20Format) support.

Could you plan to add this feature ?

Thanks.

**Comment by na-ka-na** [comment]
Thank you for the git diff integration! May I steal it?

I'll have to read up on unified format output. Thanks for the pointer. I'll keep this ticket open.

**Comment by lmazardo** [comment]
Of course, you can use the gist diff integration as you want.

**Comment by RossPatterson** [comment]
Fixed by pull request https://github.com/na-ka-na/ExcelCompare/pull/60

**Comment by r-a-i** [comment]
Hi, thank you for this amazing tool.  I installed it on mac via brew and it seems the brew package does not accept the "--diff_format=unified" flag.  Would you mind checking if the brew holds the latest greatest? Or, am I missing something?

**Comment by RossPatterson** [comment]
I guess @na-ka-na needs to make a new release and push it to brew (and any other place it goes).

**Comment by na-ka-na** [comment]
@r-a-i I've made a new release 0.7.0 and pushed to brew as well
