### ISSUE TITLE
Error on cygwin: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer

### ISSUE THREAD

**Issue by bvogler23** [na-ka-na/ExcelCompare#39]
I am having an issue using the shell script version of the tool.
I tried the following test, and it was able to run correctly.

$ cd path\to\excelcompare\bin
$ java -ea -Xmx512m -cp "dist/*" com.ka.spreadsheet.diff.SpreadSheetDiffer 1.xlsx and 2.xlsx

However when I execute from outside excelcompare/bin directory, I get the error message in the title of this issue.

Here are a few of my system settings:
$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

$ echo $PATH
/cygdrive/c/ExcelCompare-0.6.0/bin/:/cygdrive/c/ExcelCompare-0.6.0/bin/dist/:/cygdrive/c/Program Files/Java/jre1.8.0_101/bin
(only part of PATH shown)

Any help would be appreciated.

Cheers.

**Comment by na-ka-na** [comment]
Are you on windows? I don't know if PATH matters. Did you try running the excel_cmp script (or .bat on windows) instead of java directly? Even with the java command, all it needs is the path to the dist folder:

java -ea -Xmx512m -cp "/cygdrive/c/ExcelCompare-0.6.0/bin/dist/*" com.ka.spreadsheet.diff.SpreadSheetDiffer 1.xlsx 2.xlsx

**Comment by bvogler23** [comment]
I am trying to run the shell script using Cygwin. I tried replacing the shell variable "dir" with "/cygdrive/c/ExcelCompare-0.6.0/bin/" as you mentioned, however that yielded the same result.

I tried modifying the shell script as follows:
#!/usr/bin/env sh

if [ -L $0 ];then
  dir=`readlink -f $0|xargs dirname`
  echo $dir
else
  dir=`dirname $0`
  echo $dir
fi
java -ea -Xmx512m -cp "$dir/dist/*" com.ka.spreadsheet.diff.SpreadSheetDiffer "$@"

Which showed that $dir is being interpreted correctly, however, same result:
$ /cygdrive/c/ExcelCompare-0.6.0/bin/excel_cmp
/cygdrive/c/ExcelCompare-0.6.0/bin
Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer

**Comment by na-ka-na** [comment]
This is strange, not sure why cygwin matters. Can you confirm if the dist directory does have all the jars? You could also try - java -ea -Xmx512m -cp /cygdrive/c/ExcelCompare-0.6.0/bin/dist/<name of ExcelCompare.jar> com.ka.spreadsheet.diff.SpreadSheetDiffer 1.xlsx 2.xlsx. If that gives you a different error, then you may have to expand all the jar paths manually. I see a bunch of people asking how to set classpath in cygwin environment.

**Comment by bvogler23** [comment]
That gave the same error.
Here is the contents of my dist/ directory:
commons-beanutils-1.8.3.jar
java-rdfa-0.4.2.jar
poi-3.12.jar
slf4j-log4j12-1.6.4.jar
xmlbeans-2.6.0.jar
commons-digester-1.8.jar
jena-core-2.7.4.jar
poi-ooxml-3.12.jar
stax-api-1.0.1.jar
commons-logging-1.1.1.jar
jena-iri-0.9.4.jar
poi-ooxml-schemas-3.12.jar
taglets-0.8.10-incubating.jar
commons-validator-1.4.0.jar
jsr305-2.0.2.jar
simple-odf-0.8.1-incubating.jar
xercesImpl-2.9.1.jar
ExcelCompare-0.6.0.jar
odfdom-java-0.8.10-incubating.jar
slf4j-api-1.6.4.jar
xml-apis-1.3.04.jar

**Comment by Wayne-Ennis** [comment]
Was this issue ever addressed? I'm having the same problem, but can't find a resolution.

**Comment by na-ka-na** [comment]
I'm not aware of a resolution. Seems to be some fundamental difference with java classpath on cygwin.

**Comment by na-ka-na** [comment]
Someone just submitted a patch for this! If anyone is interested, you can replace your excel_cmp.sh with one from master branch, and test it out. I'm going to close this issue, please re-open if needed.
