### ISSUE TITLE
Comparing for large number of rows not happening

### ISSUE THREAD

**Issue by piyush2903** [na-ka-na/ExcelCompare#44]
I am trying to compare 2 excel files with 11680 rows and 17 Columns which never happens and after some time it shows OutOfMemoryException.
**Please find the stack trace below**
> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
>         at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRowImpl.ge
> tCArray(Unknown Source)
>         at org.apache.poi.xssf.usermodel.XSSFRow.<init>(XSSFRow.java:67)
>         at org.apache.poi.xssf.usermodel.XSSFSheet.initRows(XSSFSheet.java:238)
>         at org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:201)
>         at org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java
> :188)
>         at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkboo
> k.java:378)
>         at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:166)
>         at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:2
> 41)
>         at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.ja
> va:211)
>         at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.ja
> va:188)
>         at com.ka.spreadsheet.diff.SpreadSheetDiffer.loadSpreadSheet(SpreadSheet
> Differ.java:241)
>         at com.ka.spreadsheet.diff.SpreadSheetDiffer.doDiff(SpreadSheetDiffer.ja
> va:133)
>         at com.ka.spreadsheet.diff.SpreadSheetDiffer.doDiff(SpreadSheetDiffer.ja
> va:102)
>         at com.ka.spreadsheet.diff.SpreadSheetDiffer.main(SpreadSheetDiffer.java
> :90)

**

**Comment by na-ka-na** [comment]
Which version of ExcelCompare are you using? The latest version removes memory limit.

**Comment by piyush2903** [comment]
Good with the latest version.Closing the issue.
